server:
  port: 9092
    
eureka:
  instance:
    hostname: localhost
    port: 9090
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
   datasource:
      url: jdbc:h2:file:~/teste
      username: sa
      password:
      driver-class-name: org.h2.Driver
   jpa: 
      show-sql: true
      hibernate:
         format_sql: true
         ddl-auto: create
   h2:
      console:
         enabled: true
         path: /h2